Add support for https://github.com/DFHack/dfhack/pull/1491

diff --git a/gcc48/dfhack-test b/gcc48/dfhack-test
--- a/gcc48/dfhack-test
+++ b/gcc48/dfhack-test
@@ -66,6 +66,13 @@ run_tests()
 		dfhack_exit_code=$?
 		if [[ $dfhack_exit_code -eq $(( 666 % 256 )) ]]; then
 			: # "die" command was used; this is the expected exit code.
+		elif [[ $dfhack_exit_code -eq 102 ]]; then
+			# fatal error ('f')
+			echo "DFHack exited with code $dfhack_exit_code (fatal error in initialization)" >&2
+			echo >&2
+			echo "stderr.log follows:" >&2
+			cat stderr.log >&2
+			return 1
 		elif [[ $dfhack_exit_code -eq 124 ]]; then
 			echo "DFHack exited with code $dfhack_exit_code (timed out)" >&2
 		elif [[ $dfhack_exit_code -gt 128 && $dfhack_exit_code -lt $(( 128 + 64 )) ]]; then
